### ISSUE TITLE
Instructions d'installation manuelle manquent d'exemple

### ISSUE THREAD

**Issue by GLorieul** [michamos/vim-bepo#2]
Bonjour,

(Pas sûr qu'une issue soit le bon medium pour ma remarque?)

Juste une petite suggestion: dans les instructions d'installation du `README.md`, plutôt que d'écrire "copier tous les fichiers dans le dossier ~/.vim", ce qui m'a conduit à faire une copie de vraiment tous les fichiers i.e. `cp -r vim-bepo ~/.vim` (#noobEnVim…), peut être faudrait-il accompagner cette phrase de la commande à exécuter? (il faut copier le répertoire `after/` aussi?)

Dans tous les cas, merci pour ce dépôt!

**Comment by michamos** [comment]
Bonjour, pas de problème pour la question. Si tu fais l’installation à la main, il faut copier tous les dossiers sous `~/.vim`, donc tu dois avoir `~/.vim/plugin/`, `~/.vim/after/`, et `~/.vim/doc` à la fin.

Par contre, cette approche n’est pas vraiment conseillée. Si tu veux utiliser plusieurs plugins différents et pouvoir les mettre à jour facilement, il est vivement recommandé d’utiliser un gestionnaire de plugin, par exemple [`vim-plug`](https://github.com/junegunn/vim-plug), qui permet d’isoler les plugins et prend en charge leur installation et mise à jour à partir de déclarations dans ton `.vimrc`.

**Comment by GLorieul** [comment]
Merci pour les indications! ;)

Dans mon cas je n'utilise aucun autre plugin vim, donc la solution la plus simple à mettre en œuvre est aussi la meilleure! (malgré ses défauts…)
