### ISSUE TITLE
Problème avec netrw et Neovim 0.4.2

### ISSUE THREAD

**Issue by YoEight** [michamos/vim-bepo#5]
Bonjour.

Je rencontre un problème depuis que je suis passé à la version 0.4.2 de neovim:

![bepo](https://user-images.githubusercontent.com/144545/67465421-6b024d00-f645-11e9-9a50-ed8d4ede9e7f.png)

J'ai pu me débarrasser de ces erreur en commentant les lignes:

https://github.com/michamos/vim-bepo/blob/a4cf49526fd57bdc0e5aeee8f04b44679396acae/after/ftplugin/netrw.vim#L9
https://github.com/michamos/vim-bepo/blob/a4cf49526fd57bdc0e5aeee8f04b44679396acae/after/ftplugin/netrw.vim#L10

Cordialement

**Comment by michamos** [comment]
Bonjour, c'est réglé dans la dernière version.

**Comment by YoEight** [comment]
Merci beaucoup @michamos !
